import React from 'react';
import { Star, Quote } from 'lucide-react';

const Testimonials: React.FC = () => {
  const testimonials = [
    {
      name: 'Sarah Chen',
      role: 'CTO',
      company: 'DevFlow',
      avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'BlitzCoder cut our MVP development time from 3 weeks to 3 days. The generated FastAPI code was production-ready out of the box with proper error handling and documentation.',
      rating: 5,
      highlight: '3 weeks → 3 days'
    },
    {
      name: 'Marcus Rodriguez',
      role: 'Full-Stack Developer',
      company: 'Freelancer',
      avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'As a solo developer, BlitzCoder is like having a senior developer pair-programming with me 24/7. The code quality is exceptional and saves me hours of boilerplate work.',
      rating: 5,
      highlight: 'Like having a senior dev 24/7'
    },
    {
      name: 'Priya Patel',
      role: 'Lead Engineer',
      company: 'TechStart',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'The error detection feature saved us countless hours of debugging. It\'s like having a code review bot that never sleeps and catches issues before they reach production.',
      rating: 5,
      highlight: 'Catches bugs before production'
    },
    {
      name: 'Alex Thompson',
      role: 'DevOps Engineer',
      company: 'CloudScale',
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'The deployment configurations generated by BlitzCoder are incredibly thorough. Docker, CI/CD, monitoring - everything is set up with industry best practices.',
      rating: 5,
      highlight: 'Industry best practices'
    },
    {
      name: 'Emma Wilson',
      role: 'Startup Founder',
      company: 'InnovateAI',
      avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'BlitzCoder helped us validate our idea quickly with a working prototype. The generated React components were pixel-perfect and followed our design system perfectly.',
      rating: 5,
      highlight: 'Rapid prototyping'
    },
    {
      name: 'David Kim',
      role: 'Senior Backend Developer',
      company: 'DataDriven',
      avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'The multi-framework support is amazing. I can generate Node.js APIs and Python services with the same tool, maintaining consistency across our microservices architecture.',
      rating: 5,
      highlight: 'Multi-framework consistency'
    },
    {
      name: 'Lisa Chang',
      role: 'Product Engineer',
      company: 'BuildFast',
      avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'The AI understands context incredibly well. When I ask for an e-commerce API, it includes authentication, payment processing, and inventory management automatically.',
      rating: 5,
      highlight: 'Context-aware generation'
    },
    {
      name: 'James Miller',
      role: 'Tech Lead',
      company: 'ScaleUp',
      avatar: 'https://images.pexels.com/photos/1040880/pexels-photo-1040880.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&fit=crop',
      quote: 'Security is our top priority, and BlitzCoder generates code with proper authentication, input validation, and OWASP compliance built-in. It\'s a game-changer.',
      rating: 5,
      highlight: 'Security-first approach'
    }
  ];

  return (
    <section id="testimonials" className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Loved by <span className="gradient-text">10,000+ Developers</span>
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            See what developers around the world are saying about BlitzCoder and how it's 
            transforming their development workflow.
          </p>
        </div>

        {/* Testimonials Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {testimonials.map((testimonial, index) => (
            <div
              key={testimonial.name}
              className="bg-white rounded-xl p-6 border border-gray-200 hover:border-primary-300 hover:shadow-lg transition-all duration-300 relative group"
            >
              {/* Quote Icon */}
              <div className="absolute -top-2 -left-2 bg-primary-100 text-primary-600 p-2 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <Quote className="h-4 w-4" />
              </div>

              <div className="space-y-4">
                {/* Stars */}
                <div className="flex items-center space-x-1">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                  ))}
                </div>

                {/* Quote */}
                <p className="text-gray-700 text-sm leading-relaxed">
                  "{testimonial.quote}"
                </p>

                {/* Highlight */}
                <div className="inline-flex items-center bg-primary-50 text-primary-700 px-3 py-1 rounded-full text-xs font-semibold">
                  ⚡ {testimonial.highlight}
                </div>

                {/* Author */}
                <div className="flex items-center space-x-3 pt-2 border-t border-gray-100">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="w-10 h-10 rounded-full object-cover"
                  />
                  <div>
                    <div className="font-semibold text-gray-900 text-sm">
                      {testimonial.name}
                    </div>
                    <div className="text-gray-500 text-xs">
                      {testimonial.role} at {testimonial.company}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-16">
          <div className="bg-gradient-to-r from-primary-50 to-accent-50 rounded-2xl p-8 max-w-2xl mx-auto">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Join the Developer Revolution
            </h3>
            <p className="text-gray-600 mb-6">
              Be part of the 10,000+ developers who've already transformed their workflow with BlitzCoder.
            </p>
            <button className="btn-primary text-lg px-8 py-3">
              Start Your Free Trial
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Testimonials;